packages:
  - app
  - admin
  - packages/*
  - services
  - homepage

catalog:
  hono: 4.6.19
  react: 19.1.0
  react-dom: 19.1.0
  '@types/react': ^19.1.0
  '@types/react-dom': ^19.1.1
  wrangler: ^4.10.0
  typescript: ^5.8.2
  '@cloudflare/workers-types': ^4.20250414.0
  zod: ^3.24.1
  '@a-type/auth': 1.3.12
  '@a-type/utils': 1.1.5
  '@hono/zod-validator': ^0.4.2
  '@a-type/auth-fetch': 2.0.1
  '@react-three/fiber': 9.1.1
  '@react-three/drei': 10.0.5
  three: ^0.175.0
  '@types/three': ^0.175.0
  vitest: 3.0.8
