packages:
  - app
  - admin
  - packages/*
  - services
  - homepage

catalog:
  hono: 4.6.19
  react: 18.3.1
  react-dom: 18.3.1
  '@types/react': ^18.3.1
  '@types/react-dom': ^18.3.1
  wrangler: ^3.105.1
  typescript: ^5.7.3
  '@cloudflare/workers-types': ^4.20250124.3
  zod: ^3.24.1
  '@a-type/auth': 1.3.8
  '@a-type/utils': 1.1.4
  '@hono/zod-validator': ^0.4.2
  '@a-type/auth-fetch': ^1.0.2
  '@react-three/fiber': 8.17.12
  '@react-three/drei': ^9.121.4
  three: ^0.172.0
  '@types/three': ^0.172.0
  vitest: 3.0.8
