packages:
  - app
  - admin
  - packages/*
  - services

catalog:
  hono: 4.6.15
  react: 18.3.1
  react-dom: 18.3.1
  '@types/react': ^18.3.1
  '@types/react-dom': ^18.3.1
  wrangler: ^3.100.0
  typescript: ^5.7.2
  '@cloudflare/workers-types': ^4.20241230.0
  zod: ^3.24.0
  '@a-type/auth': 1.3.7
  '@a-type/utils': 1.1.4
  '@hono/zod-validator': ^0.4.2
  '@a-type/auth-fetch': ^1.0.1
  '@react-three/fiber': 8.16.6
  '@react-three/drei': ^9.120.8
  three: ^0.161.0
  '@types/three': ^0.172.0
