packages:
  - app
  - packages/*
  - services

catalog:
  hono: 4.6.15
  react: 19.0.0
  react-dom: 19.0.0
  '@types/react': ^19.0.0
  '@types/react-dom': ^19.0.0
  wrangler: ^3.99.0
  typescript: ^5.7.2
  '@cloudflare/workers-types': ^4.20241230.0
  zod: ^3.24.0
  '@a-type/auth': 1.2.3
  '@a-type/utils': 1.1.4
  '@hono/zod-validator': ^0.4.2
