name = "db-service"
compatibility_date = "2025-01-01"
main = "./index.ts"
account_id = "ad8af7aeb571031ffc236c411f39afe7"

[[d1_databases]]
binding = "D1"
database_name = "prod-alef-core-d1"
database_id = "7d870bc8-29bd-4e29-a6bc-13e28f6be7aa"
migrations_dir = './migrations'

[[services]]
binding = "STORE"
service = "db-service"
entrypoint = "AdminStore"

[[r2_buckets]]
bucket_name = "prod-alef-furniture-models"
binding = "FURNITURE_MODELS_BUCKET"
