name = "admin-api-service"
compatibility_date = "2025-01-01"
main = "index.ts"

compatibility_flags = ['nodejs_compat']

[[services]]
binding = "ADMIN_STORE"
service = "db-service"
entrypoint = "AdminStore"
