name = "admin-api-service"
compatibility_date = "2025-01-01"
main = "index.ts"
account_id = "ad8af7aeb571031ffc236c411f39afe7"

compatibility_flags = ['nodejs_compat']

[vars]
ADMIN_UI_ORIGIN = "https://admin.alef.io"

[[services]]
binding = "ADMIN_STORE"
service = "db-service"
entrypoint = "AdminStore"
