#:schema node_modules/wrangler/config-schema.json

name = 'alef'
compatibility_date = "2024-12-30"

[vars]
UI_ORIGIN = 'https://alef.io'
API_ORIGIN = 'https://api.alef.io'


[[d1_databases]]
binding = "DB"
database_name = "prod-alef-core-d1"
database_id = "7d870bc8-29bd-4e29-a6bc-13e28f6be7aa"
migrations_dir = './migrations'
