name = "public-api-service"
compatibility_date = "2025-01-01"
main = "index.ts"
account_id = "ad8af7aeb571031ffc236c411f39afe7"

compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.

[vars]
AWS_REGION = "us-east-2"
EMAIL_FROM = "noreply@volumetrics.io"
UI_ORIGIN = "https://app.alef.io"
ADMIN_UI_ORIGIN = "https://admin.alef.io"
API_ORIGIN = "https://api.alef.io"

[[services]]
binding = "PUBLIC_STORE"
service = "db-service"
entrypoint = "PublicStore"

[[services]]
binding = "ADMIN_STORE"
service = "db-service"
entrypoint = "AdminStore"

[[durable_objects.bindings]]
name = "DEVICE_DISCOVERY"
class_name = "DeviceDiscovery"

[[migrations]]
tag = "v1"
new_classes = ["DeviceDiscovery"]
