name = "public-api-service"
compatibility_date = "2025-01-01"
main = "index.ts"
account_id = "ad8af7aeb571031ffc236c411f39afe7"

compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.

[vars]
AWS_REGION = "us-east-2"
EMAIL_FROM = "noreply@volumetrics.io"
UI_ORIGIN = "https://app.alef.io"
ADMIN_UI_ORIGIN = "https://admin.alef.io"
API_ORIGIN = "https://api.alef.io"
HOMEPAGE_ORIGIN = "https://alef.io"
NODE_ENV = "production"

[[services]]
binding = "PUBLIC_STORE"
service = "db-service"
entrypoint = "PublicStore"

[[services]]
binding = "ADMIN_STORE"
service = "db-service"
entrypoint = "AdminStore"

[ai]
binding = "AI"

[[durable_objects.bindings]]
name = "DEVICE_DISCOVERY"
class_name = "DeviceDiscovery"

[[durable_objects.bindings]]
name = "PROPERTY"
class_name = "Property"

[[durable_objects.bindings]]
name = "PAIRCODES"
class_name = "Paircodes"

[[durable_objects.bindings]]
name = "LAYOUT_AGENT"
class_name = "LayoutAgent"

[[durable_objects.bindings]]
name = "VIBE_CODER_AGENT"
class_name = "VibeCoderAgent"

[[migrations]]
tag = "v1"
new_classes = ["DeviceDiscovery"]

[[migrations]]
tag = "v2"
new_classes = ["Property"]

[[migrations]]
tag = "v3"
new_classes = ["Paircodes"]

[[migrations]]
tag = "v4"
new_sqlite_classes = ["LayoutAgent"]

[[migrations]]
tag = "v5"
new_sqlite_classes = ["VibeCoderAgent"]
