name = "db-service"
compatibility_date = "2025-01-01"
main = "src/index.ts"
node_compat = true

[[d1_databases]]
binding = "D1"
database_name = "prod-alef-core-d1"
database_id = "7d870bc8-29bd-4e29-a6bc-13e28f6be7aa"
migrations_dir = './migrations'

[[services]]
binding = "STORE"
service = "db-service"
entrypoint = "AdminStore"
