name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
      - name: Install deps
        run: pnpm install
      - name: Build everything
        run: pnpm run build
        env:
          VITE_PUBLIC_API_ORIGIN: ${{ vars.PUBLIC_API_ORIGIN }}
          VITE_ADMIN_API_ORIGIN: ${{ vars.ADMIN_API_ORIGIN }}
          VITE_MAIN_UI_ORIGIN: ${{ vars.APP_ORIGIN }}
          VITE_ADMIN_UI_ORIGIN: ${{ vars.ADMIN_APP_ORIGIN }}

      - name: Verify cloudflare token
        run: |
          curl -X GET "https://api.cloudflare.com/client/v4/user/tokens/verify" \
          -H "Authorization: Bearer ${{secrets.CLOUDFLARE_API_TOKEN}}" \
          -H "Content-Type:application/json"

      - name: Deploy DB
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          packageManager: pnpm
          workingDirectory: ./services
          command: deploy -c ./src/db/wrangler.toml
      - name: Deploy Public API
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          packageManager: pnpm
          workingDirectory: ./services
          command: deploy -c ./src/public-api/wrangler.toml
      - name: Deploy Admin API
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          packageManager: pnpm
          workingDirectory: ./services
          command: deploy -c ./src/admin-api/wrangler.toml

      - name: Deploy Public App
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          packageManager: pnpm
          workingDirectory: ./app
          command: pages deploy dist --project-name=app
      - name: Deploy Admin App
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          packageManager: pnpm
          workingDirectory: ./admin
          command: pages deploy dist --project-name=admin

      - name: Deploy homepage
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          packageManager: pnpm
          workingDirectory: ./homepage
          command: pages deploy dist --project-name=homepage

      - name: 'Deploy cron: cleanup unused attributes'
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          packageManager: pnpm
          workingDirectory: ./services
          command: deploy -c ./src/cron/cleanup-unused-attrs/wrangler.toml
